version: '3'
services:
  tender-docxtemplate:
    container_name: tender-docxtemplate-app
    image: ghcr.io/kiennkt/kiennkt/tender_document_generator:latest
    ports:
      - 8503:8503
    restart: always
    volumes:
      - tender_data:/tender-docxtemplate-app

volumes:
  tender_data:  
